[project]
name = "hm1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "parquet-tools>=0.2.16",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.6.1",
]
